#!/usr/bin/env python3
"""Close the build's module hierarchy offline, without Vivado.

Reads the manifest, parses every Verilog source in it, and walks the design from the real board top
(`rocketchip_wrapper`). It answers four questions that decide whether the file list is actually buildable:

  * is every instantiated module either defined in the list, or on the short whitelist of things Vivado
    supplies itself (Xilinx primitives and the block design)?
  * is any module defined twice? In particular, is the baseline Rocket `Top` in the list alongside the shim?
  * does the walk reach the teaching design -- TeachingBoardTop, TeachingCpu, tcpu_core -- from the board
    top, through the shim?
  * is anything from the Rocket subsystem (FPGAZynqTop and friends) reachable?

  check-hierarchy.py <MANIFEST> [--drop <path>]... [--add <path>]... [--expect-fail]

--drop and --add exist so the negative tests run through this same code, not a copy of it.
"""
import re, sys, os, argparse

ap=argparse.ArgumentParser()
ap.add_argument("manifest"); ap.add_argument("--drop", action="append", default=[])
ap.add_argument("--add", action="append", default=[]); ap.add_argument("--quiet", action="store_true")
ap.add_argument("--top", default="rocketchip_wrapper",
                help="the top to walk from; changing it is for testing the parser, not for checking a build")
a=ap.parse_args()

# Vivado supplies these; they are not expected in the file list.
PRIMITIVES={"IBUFG","IBUFDS","BUFG","BUFGCE","BUFR","BUFIO","MMCME2_BASE","MMCME2_ADV","PLLE2_BASE",
            "IBUF","OBUF","IOBUF","OBUFT","FDRE","FDSE","LUT1","LUT2","LUT3","LUT4","LUT5","LUT6",
            "RAMB18E1","RAMB36E1","DSP48E1","PS7","IDELAYCTRL","STARTUPE2","BUFGMUX","ODDR","IDDR"}
BD_MODULES={"system"}   # generated by src/tcl/pynqz1_bd.tcl, which the manifest carries
KEYWORDS={"module","endmodule","input","output","inout","wire","reg","integer","real","time","parameter",
          "localparam","assign","always","initial","begin","end","if","else","case","casex","casez",
          "endcase","for","while","repeat","forever","function","endfunction","task","endtask","generate",
          "endgenerate","genvar","posedge","negedge","or","and","not","xor","nand","nor","xnor","buf",
          "defparam","specify","endspecify","default","signed","unsigned","return","disable","wait",
          "force","release","assign","deassign","fork","join","supply0","supply1","tri","wand","wor",
          "pulldown","pullup","primitive","endprimitive","table","endtable","include","define","timescale"}

files=[]; roles={}
for line in open(a.manifest):
    if line.startswith("#") or not line.strip(): continue
    role,sha,size,path,*rest=line.rstrip("\n").split("\t")
    files.append(path); roles[path]=role
for p in a.drop:
    files=[f for f in files if os.path.abspath(f)!=os.path.abspath(p)]
files+= a.add
verilog=[f for f in files if f.endswith((".v",".sv"))]

def strip(src):
    src=re.sub(r"/\*.*?\*/","",src,flags=re.S)
    src=re.sub(r"//[^\n]*","",src)
    src=re.sub(r'"[^"\n]*"','""',src)
    return src

defs={}; insts={}
for f in verilog:
    if not os.path.isfile(f): print(f"FAIL: listed but missing: {f}"); sys.exit(1)
    s=strip(open(f, errors="replace").read())
    cur=None
    # An instantiation is `Name [#(params)] inst [range] (`. Points that cost real detections when got
    # wrong, each one covered by a case in scripts/selftest.sh:
    #   * whitespace between the two identifiers must be required -- without it `for (i` parses as a
    #     module `fo` instantiated as `r`;
    #   * that whitespace may contain a newline: the module name and the instance name are not always on
    #     the same line;
    #   * an instance array (`mod inst [3:0] (`) is still an instantiation.
    for m in re.finditer(r"\bmodule\s+(\w+)|\bendmodule\b"
                         r"|^[ \t]*(\w+)\s+(?:#\s*\([^;]*?\)\s*)?(\w+)\s*(?:\[[^\];]*\]\s*)?\(",
                         s, re.M):
        if m.group(1):
            cur=m.group(1); defs.setdefault(cur,[]).append(f)
        elif m.group(0).strip()=="endmodule":
            cur=None
        elif cur and m.group(2) and m.group(2) not in KEYWORDS and m.group(3) not in KEYWORDS \
                 and not m.group(2).startswith("$"):
            insts.setdefault(cur,set()).add(m.group(2))

fails=[]
print(f"## {len(verilog)} Verilog sources, {len(defs)} module definitions")
dup={k:v for k,v in defs.items() if len(v)>1}
print(f"## modules defined more than once: {len(dup)}")
for k,v in dup.items():
    print(f"   FAIL: {k} defined in {len(v)} files:")
    for f in v: print(f"         {f}")
    fails.append(f"duplicate definition of {k}")

TOP=a.top
if TOP not in defs: print(f"   FAIL: the board top {TOP} is not in the file list"); fails.append("no board top")
seen=set(); unresolved={}; stack=[TOP] if TOP in defs else []
while stack:
    m=stack.pop()
    if m in seen: continue
    seen.add(m)
    for c in sorted(insts.get(m,())):
        if c in defs: stack.append(c)
        elif c in PRIMITIVES or c in BD_MODULES: pass
        else: unresolved.setdefault(c,set()).add(m)
print(f"## reachable from {TOP}: {len(seen)} modules")
print(f"## unresolved instantiations: {len(unresolved)}")
for c,parents in sorted(unresolved.items()):
    print(f"   FAIL: {c} instantiated in {sorted(parents)} but defined nowhere in the list")
    fails.append(f"unresolved {c}")
prim=sorted({c for m in seen for c in insts.get(m,()) if c in PRIMITIVES})
bd=sorted({c for m in seen for c in insts.get(m,()) if c in BD_MODULES})
print(f"   supplied by Vivado : {prim}")
print(f"   supplied by the BD : {bd}   (from {os.path.basename([f for f in files if f.endswith('bd.tcl')][0]) if any(f.endswith('bd.tcl') for f in files) else 'NOTHING -- the bd tcl is not in the manifest'})")
if not any(f.endswith("bd.tcl") for f in files) and bd: fails.append("bd tcl missing from the manifest")

if a.top!="rocketchip_wrapper":
    print(f"\n(parser probe mode: walked from {a.top}, so the board-level checks below are skipped)")
    print(f"HIERARCHY_CHECK fails={len(fails)}" + (": "+"; ".join(fails[:6]) if fails else ""))
    sys.exit(1 if fails else 0)
print("## the path the board top takes into the teaching design")
want=["Top","RD2BoardTop","RD2ZynqTop","TeachingCpuV2","tcpu_core","tcpu_csr","tcpu_regfile","tcpu_muldiv","tcpu_cdecode","tcpu_ptw"]  # atomic copy: new top names, and the six black boxes rather than three
for w in want:
    where=defs.get(w,[])
    ok = w in seen and len(where)==1
    print(f"   {w:20s} {'reached' if w in seen else 'NOT REACHED':11s}  defined in {os.path.basename(where[0]) if len(where)==1 else where}")
    if not ok: fails.append(f"{w} not reached or not uniquely defined")
if "Top" in defs and len(defs["Top"])==1:
    src=defs["Top"][0]
    if "shim" not in os.path.basename(src):
        print(f"   FAIL: `Top` comes from {src}, which is not the generated shim")
        fails.append("Top is not the shim")
print("## anything from the Rocket subsystem must be absent")
rocket=[m for m in ("FPGAZynqTop","FPGAZynqTopModule","RocketTile","Rocket") if m in defs]
print(f"   Rocket modules in the list: {rocket if rocket else 'none'}")
if rocket: fails.append("Rocket subsystem modules present")

print(f"\nHIERARCHY_CHECK fails={len(fails)}" + (": "+"; ".join(fails[:6]) if fails else ""))
sys.exit(1 if fails else 0)
