#!/usr/bin/env python3
"""Generate the isolation layer (atomic board copy: the module name is a parameter) that lets the real board wrapper drive the teaching design.

The board's true top is `rocketchip_wrapper`: it carries the PS block design, the board pins, the MMCM and
the two AXI boundaries. It instantiates a module called `Top`. Rather than edit that file -- it is baseline
and read-only -- or point the project's top at `TeachingBoardTop` (which would throw the whole board level
away), this emits a `Top` whose only job is to pass its ports through to `TeachingBoardTop`.

The port list is not typed by hand: it is read out of the baseline `Top` and the generated teaching top,
and the two must agree exactly or nothing is written.

  make-top-shim.py <TeachingBoardTop....v> <out.v> [--baseline <Top.ZynqFPGAConfig.v>]
"""
import re, sys, os, argparse, hashlib, datetime

ap=argparse.ArgumentParser()
ap.add_argument("teaching"); ap.add_argument("out")
ap.add_argument("--top", default="RD2BoardTop")   # the m4 script hardcoded TeachingBoardTop
ap.add_argument("--baseline", default="/home/engineer/fpga/teaching-cpu-work/fpga-zynq/pynqz1/src/verilog/Top.ZynqFPGAConfig.v")
a=ap.parse_args()
a.teaching=os.path.abspath(a.teaching)
a.baseline=os.path.abspath(a.baseline)

def ports(path, mod):
    src=open(path, errors="replace").read()
    m=re.search(rf"^module {mod}\((.*?)\);", src, re.S|re.M)
    if not m: sys.exit(f"no module {mod} in {path}")
    out=[]
    for line in m.group(1).splitlines():
        p=re.match(r"\s*(input|output|inout)\s+(\[[^\]]*\]\s*)?(\w+)", line)
        if p: out.append((p.group(1), (p.group(2) or "").strip(), p.group(3)))
    if not out: sys.exit(f"no ports parsed from {mod} in {path}")
    return out

base=ports(a.baseline, "Top")
teach=ports(a.teaching, a.top)
if base!=teach:
    print(f"REFUSE: the teaching top does not match the baseline Top port for port")
    for i,(x,y) in enumerate(zip(base,teach)):
        if x!=y: print(f"  [{i}] baseline {x}   teaching {y}")
    if len(base)!=len(teach): print(f"  and the counts differ: {len(base)} vs {len(teach)}")
    sys.exit(1)

def h(p): return hashlib.sha256(open(p,'rb').read()).hexdigest()
decls=",\n".join(f"  {d:6s} {w:9s} {n}" for d,w,n in base)
conns=",\n".join(f"    .{n}({n})" for _,_,n in base)
open(a.out,"w").write(f"""// Generated by scripts/make-top-shim.py -- do not edit by hand.
//
// The isolation layer between the board wrapper and the teaching design. `rocketchip_wrapper` instantiates
// a module named `Top`; this is that module, and it does nothing but connect its {len(base)} ports straight
// through to `TeachingBoardTop`. The board level -- PS, board pins, MMCM, the two AXI boundaries -- stays
// exactly where it was, and no baseline file is modified.
//
// The baseline `Top` (the Rocket one) must NOT be in the same project: two definitions of `Top` would be a
// collision, and scripts/check-hierarchy.py fails if it finds one.
//
// generated  {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}
// from       {a.teaching}
//            sha256 {h(a.teaching)}
// checked against the baseline port list of
//            {a.baseline}
//            sha256 {h(a.baseline)}
// ports      {len(base)}, identical field for field

module Top(
{decls}
);

  {a.top} teaching_board_top(
{conns}
  );

endmodule
""")
print(f"SHIM_OK {len(base)} ports -> {a.out}")
