// Top level for simulation: parameters are overridden per timing/fault configuration with -G.
`timescale 1ns/1ps
module TeachingTop #(
  parameter READY_DELAY  = 0,
  parameter RESP_DELAY   = 1,
  parameter RANDOM       = 0,
  parameter SEED         = 1,
  parameter X0_WRITABLE  = 0,
  parameter NO_LOAD_SEXT = 0,
  parameter MEM_SAME_CYCLE = 0,
  parameter REQ_WITHDRAW = 0,
  parameter LOAD_WDATA_LEAK = 0,
  parameter TAIL_ERR = 0,
  parameter TAIL_DROP = 0,
  parameter STOP_ON_TRAP = 0,
  parameter TRAP_BAD_MEPC = 0,
  parameter TRAP_COUNTS_RET = 0,
  parameter FAULT_W_SEXT = 0,      // CPU-M fault injection
  parameter FAULT_MULH_SIGN = 0,
  parameter FAULT_C_IMM = 0,       // CPU-C fault injection
  parameter FAULT_C_REG = 0,
  parameter FAULT_NO_DELEG = 0,     // CPU-SU fault injection
  parameter FAULT_S_IRQ_IN_M = 0,
  parameter FAULT_SRET_SPP = 0,
  parameter FAULT_PTW_NO_PERM = 0,  // CPU-SV39 fault injection
  parameter FAULT_IF2_NO_XLATE = 0,
  parameter FAULT_PPN_TRUNC = 0,
  parameter ALLOW_RO_WRITE = 0,
  parameter FETCH_ERR_AFTER = 0,
  parameter FETCH_ERR_ADDR = 0,
  parameter EARLY_IRQ = 0,
  parameter IRQ_BAD_MEPC = 0,
  parameter STALE_MIE = 0,
  parameter IRQ_POINT = 0,
  parameter IRQ_LINE = 0,
  parameter IRQ_TIMES = 1,
  parameter IRQ_AFTER = 0,
  parameter IRQ_ARM_REQUIRED = 0,
  parameter IRQ_NEED_ENABLED = 0,
  parameter DUP_STORE = 0,
  parameter IRQ_NEED_WRITE = 0,
  parameter IRQ_ALL_LINES = 0,
  // CPU-A
  parameter EXT_POINT = 0,
  parameter EXT_TIMES = 1,
  parameter EXT_AT_CYCLE = 0,
  parameter EXT_AFTER = 0,
  parameter EXT_ADDR = 32'h8000_0100,
  parameter EXT_DATA = 64'hAAAA_AAAA_AAAA_AAAA,
  parameter FAULT_MODEL_NO_KILL = 0,
  parameter FAULT_MODEL_SC_ALWAYS_OK = 0,
  parameter MISA_A = 0,
  parameter FAULT_A_W_NOSEXT = 0,
  parameter FAULT_A_SC_RESULT = 0,
  parameter FAULT_A_AMO_AS_LOAD = 0,
  parameter FAULT_A_EARLY_RETIRE = 0,
  parameter FAULT_A_NO_RESV_CLEAR = 0
) (
  input clk, input rst,
  input bd_we, input [15:0] bd_addr, input [63:0] bd_data,
  input [15:0] bd_rd_addr, output [63:0] bd_rd_data,
  input [31:0] bd_fault_addr, input [31:0] bd_watch_addr, input [63:0] bd_inject_pc,
  input bd_core_rst, output [3:0] cpu_state_o, output [63:0] cpu_pc_o,
  input [4:0] bd_reg_addr, output [63:0] bd_reg_data,
  input [4:0] bd_csr_sel, output [63:0] bd_csr_data, output [1:0] cpu_priv_o,
  output commit_valid, output [63:0] commit_pc, output [31:0] commit_insn, output [2:0] commit_len,
  output commit_rd_valid, output [4:0] commit_rd, output [63:0] commit_rd_data,
  output trap_valid, output trap_interrupt, output [63:0] trap_cause, output [63:0] trap_epc, output [63:0] trap_tval,
  output halted, output [63:0] proto_errors, output [63:0] n_req, output [63:0] n_resp,
  output [63:0] n_data_req, output [63:0] obs_errors, output [63:0] n_discard,
  output [63:0] irq_hits, output [63:0] irq_fires, output [63:0] irq_clears,
  output [63:0] fire_cycle, output [63:0] fire_pc, output [3:0] fire_state,
  output fire_enabled, output [1:0] fire_priv, output fire_req_valid, output fire_req_ready, output fire_outstanding,
  output fire_is_write, output [31:0] fire_addr,
  output [63:0] apply_seq, output [63:0] apply1_cycle, output [63:0] apply2_cycle,
  output [63:0] apply1_data, output [63:0] apply2_data,
  output [63:0] watch_req, output [63:0] watch_wreq, output [63:0] watch_resp, output [63:0] watch_writes
);
  tcpu_harness #(.READY_DELAY(READY_DELAY), .RESP_DELAY(RESP_DELAY), .RANDOM(RANDOM), .SEED(SEED),
                 .X0_WRITABLE(X0_WRITABLE), .NO_LOAD_SEXT(NO_LOAD_SEXT),
                 .MEM_SAME_CYCLE(MEM_SAME_CYCLE), .REQ_WITHDRAW(REQ_WITHDRAW),
                 .LOAD_WDATA_LEAK(LOAD_WDATA_LEAK), .TAIL_ERR(TAIL_ERR), .TAIL_DROP(TAIL_DROP),
                 .STOP_ON_TRAP(STOP_ON_TRAP), .TRAP_BAD_MEPC(TRAP_BAD_MEPC),
                 .TRAP_COUNTS_RET(TRAP_COUNTS_RET), .ALLOW_RO_WRITE(ALLOW_RO_WRITE), .FAULT_W_SEXT(FAULT_W_SEXT), .FAULT_MULH_SIGN(FAULT_MULH_SIGN), .FAULT_C_IMM(FAULT_C_IMM), .FAULT_C_REG(FAULT_C_REG),
                 .FAULT_NO_DELEG(FAULT_NO_DELEG), .FAULT_S_IRQ_IN_M(FAULT_S_IRQ_IN_M), .FAULT_SRET_SPP(FAULT_SRET_SPP),
                 .FAULT_PTW_NO_PERM(FAULT_PTW_NO_PERM), .FAULT_IF2_NO_XLATE(FAULT_IF2_NO_XLATE), .FAULT_PPN_TRUNC(FAULT_PPN_TRUNC),
                 .FETCH_ERR_AFTER(FETCH_ERR_AFTER), .FETCH_ERR_ADDR(FETCH_ERR_ADDR), .EARLY_IRQ(EARLY_IRQ),
                 .IRQ_BAD_MEPC(IRQ_BAD_MEPC), .STALE_MIE(STALE_MIE),
                 .IRQ_POINT(IRQ_POINT), .IRQ_LINE(IRQ_LINE), .IRQ_TIMES(IRQ_TIMES), .IRQ_AFTER(IRQ_AFTER), .IRQ_ARM_REQUIRED(IRQ_ARM_REQUIRED), .IRQ_NEED_ENABLED(IRQ_NEED_ENABLED),
                 .DUP_STORE(DUP_STORE), .IRQ_NEED_WRITE(IRQ_NEED_WRITE),
                 .IRQ_ALL_LINES(IRQ_ALL_LINES),
                 .EXT_POINT(EXT_POINT), .EXT_TIMES(EXT_TIMES), .EXT_AT_CYCLE(EXT_AT_CYCLE), .EXT_AFTER(EXT_AFTER),
                 .EXT_ADDR(EXT_ADDR), .EXT_DATA(EXT_DATA),
                 .FAULT_MODEL_NO_KILL(FAULT_MODEL_NO_KILL), .FAULT_MODEL_SC_ALWAYS_OK(FAULT_MODEL_SC_ALWAYS_OK),
                 .MISA_A(MISA_A), .FAULT_A_W_NOSEXT(FAULT_A_W_NOSEXT), .FAULT_A_SC_RESULT(FAULT_A_SC_RESULT),
                 .FAULT_A_AMO_AS_LOAD(FAULT_A_AMO_AS_LOAD), .FAULT_A_EARLY_RETIRE(FAULT_A_EARLY_RETIRE),
                 .FAULT_A_NO_RESV_CLEAR(FAULT_A_NO_RESV_CLEAR)) h (
    .clk(clk), .rst(rst), .bd_we(bd_we), .bd_addr(bd_addr), .bd_data(bd_data),
    .bd_rd_addr(bd_rd_addr), .bd_rd_data(bd_rd_data), .bd_fault_addr(bd_fault_addr),
    .bd_watch_addr(bd_watch_addr), .bd_inject_pc(bd_inject_pc),
    .bd_core_rst(bd_core_rst), .cpu_state_o(cpu_state_o), .cpu_pc_o(cpu_pc_o), .bd_reg_addr(bd_reg_addr), .bd_reg_data(bd_reg_data),
    .bd_csr_sel(bd_csr_sel), .bd_csr_data(bd_csr_data), .cpu_priv_o(cpu_priv_o),
    .commit_valid(commit_valid), .commit_pc(commit_pc), .commit_insn(commit_insn), .commit_len(commit_len),
    .commit_rd_valid(commit_rd_valid), .commit_rd(commit_rd), .commit_rd_data(commit_rd_data),
    .trap_valid(trap_valid), .trap_interrupt(trap_interrupt), .trap_cause(trap_cause), .trap_epc(trap_epc), .trap_tval(trap_tval),
    .halted(halted), .proto_errors(proto_errors), .n_req(n_req), .n_resp(n_resp), .n_data_req(n_data_req), .obs_errors(obs_errors), .n_discard(n_discard),
    .irq_hits(irq_hits), .irq_fires(irq_fires), .irq_clears(irq_clears),
    .fire_cycle(fire_cycle), .fire_pc(fire_pc), .fire_state(fire_state), .fire_enabled(fire_enabled), .fire_priv(fire_priv),
    .fire_req_valid(fire_req_valid), .fire_req_ready(fire_req_ready), .fire_outstanding(fire_outstanding),
    .fire_is_write(fire_is_write), .fire_addr(fire_addr),
    .apply_seq(apply_seq), .apply1_cycle(apply1_cycle), .apply2_cycle(apply2_cycle),
    .apply1_data(apply1_data), .apply2_data(apply2_data),
    .watch_req(watch_req), .watch_wreq(watch_wreq), .watch_resp(watch_resp), .watch_writes(watch_writes));
endmodule
