#!/usr/bin/env python3
"""Emit the independent Vivado project script for the teaching build, straight from the manifest.

Nothing here runs Vivado. The point of generating the Tcl rather than writing it by hand is that the file
list in the project and the file list in the manifest cannot drift apart: both come from the same source,
and the shell wrapper re-checks every hash before it would hand the script to Vivado.

What the emitted script does *not* do: touch the baseline project, the baseline wrapper, or
Top.ZynqFPGAConfig.v. It creates a new project directory and refuses to start if that directory exists.

  gen-project-tcl.py <MANIFEST> <out.tcl> [--project-dir <dir>]
"""
import sys, os, argparse, datetime

ap=argparse.ArgumentParser()
ap.add_argument("manifest"); ap.add_argument("out")
ap.add_argument("--project-dir", default="/home/engineer/fpga/experiments/teaching-cpu/m4-build/project")
ap.add_argument("--board-repo", default="/home/engineer/fpga/board_files")
a=ap.parse_args()
a.manifest=os.path.abspath(a.manifest)

rows=[]
for line in open(a.manifest):
    if line.startswith("#") or not line.strip(): continue
    role,sha,size,path,*rest=line.rstrip("\n").split("\t")
    rows.append((role,sha,path))
by=lambda r: [p for role,_,p in rows if role==r]
srcs = by("shim") + by("board-rtl") + by("wrapper") + by("blackbox") + by("support")
incdirs = sorted({os.path.dirname(p) for p in by("include")})
xdc = by("xdc"); bd = by("bd-tcl")
for name,lst in (("shim",by("shim")),("board-rtl",by("board-rtl")),("wrapper",by("wrapper")),
                 ("xdc",xdc),("bd-tcl",bd)):
    if len(lst)!=1: sys.exit(f"REFUSE: expected exactly one {name} in the manifest, found {len(lst)}")
if not by("blackbox"): sys.exit("REFUSE: no black-box RTL in the manifest")

files_tcl="\n".join(f'  "{p}" \\' for p in srcs)
inc_tcl=" ".join(f'"{d}"' for d in incdirs)
gen=datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
open(a.out,"w").write(f"""# Generated by scripts/gen-project-tcl.py on {gen} -- do not edit by hand.
# Source of truth for the file list: {a.manifest}
#
# An independent project for the teaching design. The board top stays `rocketchip_wrapper`: the PS block
# design, the board pins, the MMCM and both AXI boundaries are the baseline's, unmodified. What changes is
# one level down -- the `Top` in this project is the generated shim, which passes through to
# TeachingBoardTop, and the baseline Top.ZynqFPGAConfig.v is deliberately absent.
#
# Not run by anything in M4-a. M4-b runs it, under the vivado lease, with separate authorisation.

set proj_dir "{a.project_dir}"
if {{[file exists $proj_dir]}} {{
  puts "REFUSE: $proj_dir already exists; this script will not write into an existing build"
  exit 2
}}
set_param board.repoPaths [list "{a.board_repo}"]

create_project teaching_pynqz1 $proj_dir -part xc7z020clg400-1
set obj [get_projects teaching_pynqz1]
set_property "default_lib" "xil_defaultlib" $obj
set_property "board_part" "www.digilentinc.com:pynq-z1:part0:1.0" $obj
set_property "simulator_language" "Mixed" $obj

# ---- sources, in the order the manifest lists them -------------------------------------------------
set files [list \\
{files_tcl}
]
add_files -norecurse -fileset [get_filesets sources_1] $files

# the include path for tcpu_defs.vh and clocking.vh
set_property include_dirs [list {inc_tcl}] [get_filesets sources_1]

# SYNTHESIS is defined explicitly rather than relied upon. Whether Vivado predefines it is not something
# this project should depend on: with it defined, every `ifndef SYNTHESIS` region -- the simulation
# printfs, the $fatal/$finish calls, plusarg_reader's $value$plusargs branch -- is excluded at parse time.
# The baseline project does not set this, and is not modified.
set_property verilog_define {{SYNTHESIS}} [get_filesets sources_1]

set_property "top" "rocketchip_wrapper" [get_filesets sources_1]

# the baseline Rocket top must not be here: two definitions of `Top` would collide
foreach f [get_files -quiet *Top.ZynqFPGAConfig.v] {{
  puts "REFUSE: the baseline Rocket top is in this project: $f"
  exit 2
}}

# ---- constraints ------------------------------------------------------------------------------------
if {{[string equal [get_filesets -quiet constrs_1] ""]}} {{ create_fileset -constrset constrs_1 }}
add_files -norecurse -fileset [get_filesets constrs_1] "{xdc[0]}"
set_property "file_type" "XDC" [get_files -of_objects [get_filesets constrs_1] "{xdc[0]}"]
set_property "target_constrs_file" "{xdc[0]}" [get_filesets constrs_1]

# ---- runs -------------------------------------------------------------------------------------------
if {{[string equal [get_runs -quiet synth_1] ""]}} {{
  create_run -name synth_1 -part xc7z020clg400-1 -flow {{Vivado Synthesis 2015}} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
}}
if {{[string equal [get_runs -quiet impl_1] ""]}} {{
  create_run -name impl_1 -part xc7z020clg400-1 -flow {{Vivado Implementation 2015}} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
}}

# ---- the PS block design, from the baseline script, unmodified ---------------------------------------
puts "INFO: recreating the block design from {bd[0]}"
source "{bd[0]}"

# The PS7 preset check from build_2025.tcl: with the board file absent the automation silently applies
# nothing and the failure only shows up on hardware as a garbled console.
set ps [get_bd_cells -quiet processing_system7_0]
if {{$ps eq ""}} {{
  puts "FAIL: no processing_system7_0 cell -- the block design did not build"
  exit 3
}}
set xtal [get_property -quiet CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ $ps]
if {{$xtal != 50}} {{
  puts "FAIL: crystal is <$xtal>, expected 50 -- the Digilent preset did not apply"
  exit 3
}}
puts "PASS: crystal is 50 MHz -- the Digilent preset applied"

puts "PROJECT_CREATED $proj_dir"
""")
print(f"PROJECT_TCL_OK {len(srcs)} sources, {len(incdirs)} include dirs -> {a.out}")
